[[session]]
name = "config"
startup_command = "tmux select-window -t dotfiles; exit"
windows = ["dotfiles", "homelab"]

[[session]]
name = "homelab"
startup_command = "ssh homelab"

[[session]]
name = "work"
startup_command = "tmux select-window -t cloud-java; exit"
windows = ["cloud-java", "cloud-go", "bootstrap-templates", "salt-formula"]

[[window]]
name = "cloud-java"
path = "~/cloudia/cloud/cloud-java"
startup_script = "tmux split-window -v -t cloud-java -p 30"

[[window]]
name = "cloud-go"
path = "~/cloudia/cloud/cloud-go"
startup_script = "tmux split-window -v -t cloud-go -p 30"

[[window]]
name = "bootstrap-templates"
path = "~/cloudia/cloud/deploy/bootstrap/templates"

[[window]]
name = "salt-formula"
path = "~/cloudia/cloud/deploy/salt-formula"

[[window]]
name = "dotfiles"
path = "~/dotfiles"
startup_script = "tmux split-window -v -t dotfiles -p 30; nvim"

[[window]]
name = "homelab"
path = "~/dev/github.com/damirm/homelab"
startup_script = "tmux split-window -v -t homelab -p 30; nvim"
