# cask_args appdir: "~/Applications", require_sha: true

# Editors
brew "neovim"
# brew "helix"
# brew "micro"
# brew "kakoune"

brew "ncdu"
brew "lnav"
brew "hl"

# k8s
brew "kubernetes-cli"
brew "helmfile"
brew "helm"

brew "stow"
brew "ansible"
brew "fzf"
brew "git"
brew "ollama"
brew "bat"
brew "glow"
# TODO: Use mise.
brew "bazel"
# TODO: Use mise.
brew "biome"
brew "tealdeer"
brew "tmux"
# TODO: Add explicit tap.
brew "joshmedeski/sesh/sesh"
brew "tree"
brew "htop"
brew "coreutils"
brew "uv"
brew "ctop"
brew "d2"
brew "wget"
brew "curl"
brew "wrk"
brew "jq"
brew "yq"
brew "xplr"
brew "k6"
brew "ripgrep"
brew "duf"
brew "dust"
brew "dua-cli"
brew "lazydocker"
brew "lazygit"
brew "eza"
# TODO: Use mise.
brew "ruff"
brew "lf"
brew "zx"
brew "fx"
brew "fd"
brew "micronaut"
brew "zoxide"
brew "x-cmd"

brew "zsh"
brew "bash"
brew "starship"
brew "mise"

# Casks"

cask "firefox"
cask "google-chrome"

# cask "font-hack-nerd-font"
# cask "font-jetbrains-mono"
cask "font-jetbrains-mono-nerd-font"

# Productivity
cask "zoom"
cask "todoist"
cask "obsidian"
cask "affine"
cask "anytype"
cask "appflowy"
cask "joplin"
cask "siyuan"
cask "notion"
cask "itsycal"
cask "raycast"
cask "shottr"
cask "telegram-desktop"

cask "1password"
cask "bitwarden"
cask "hiddenbar"
cask "keepingyouawake"
cask "love"
cask "processing"
cask "beekeeper-studio"
cask "vlc"
cask "macfuse"
# cask "chatbox"

# Terminal
cask "alacritty"
# cask "ghostty"
# cask "wezterm"
# cask "kitty"

# Tiling window manager
# cask "amethyst"
cask "rectangle"

cask "visual-studio-code"
cask "intellij-idea-ce"

cask "ledger-live"
