return {
	"nvim-treesitter/nvim-treesitter",
	build = ":TSUpdate",
	main = "nvim-treesitter.configs",
	lazy = false,
	opts = {
		ensure_installed = {
			"bash",
			"c",
			"cmake",
			"cpp",
			"css",
			"cue",
			"dart",
			"dockerfile",
			"editorconfig",
			"gitignore",
			"go",
			"gomod",
			"gosum",
			"hcl",
			"helm",
			"html",
			"java",
			"javascript",
			"jinja",
			"json",
			"kotlin",
			"lua",
			"make",
			"markdown",
			"mermaid",
			"nginx",
			"nim",
			"odin",
			"proto",
			"python",
			"rust",
			"scss",
			"solidity",
			"sql",
			"svelte",
			"swift",
			"templ",
			"terraform",
			"tmux",
			"toml",
			"tsx",
			"typescript",
			"typst",
			"v",
			"vue",
			"xml",
			"yaml",
			"zig",
		},
		auto_install = true,
		incremental_selection = {
			enable = true,
			keymaps = {
				init_selection = "gnn",
				node_incremental = "grn",
				scope_incremental = "grc",
				node_decremental = "grm",
			},
		},
		indent = {
			enable = true,
		},
		highlight = {
			enable = true,
			-- Setting this to true will run `:h syntax` and tree-sitter at the same time.
			-- Set this to `true` if you depend on 'syntax' being enabled (like for indentation).
			-- Using this option may slow down your editor, and you may see some duplicate highlights.
			-- Instead of true it can also be a list of languages
			additional_vim_regex_highlighting = false,
		},
	},
	config = function(_, opts)
		require("nvim-treesitter.configs").setup(opts)
	end,
}
